[build]
  command = "npm install && npm run build"
  functions = "functions"

[[redirects]]
  from = "/"
  to = "https://www.pushquantum.tech/qel"
  status = 302
  force = true # COMMENT: ensure that we always redirect